// This file is autogenerated. Changes will be overwritten.
#include "VU2PALRVTW/moc_ipcclient.cpp"
#include "VU2PALRVTW/moc_reader.cpp"
#include "VU2PALRVTW/moc_speedprovider.cpp"
#include "VU2PALRVTW/moc_systemstatus.cpp"
#include "VU2PALRVTW/moc_temperatureprovider.cpp"
#include "VU2PALRVTW/moc_timeprovider.cpp"
