[system]
compatible=seame-rpi5
bootloader=custom

[keyring]
path=/etc/rauc/ca.cert.pem

[handlers]
bootloader-custom-backend=/usr/lib/rauc/bootloader-noop.sh

[slot.rootfs.0]
device=/dev/mmcblk0p2
type=ext4
bootname=A

[slot.appfs.0]
device=/data/rauc-slot.img
type=raw
